import Head from 'next/head'
import React, { ReactNode } from 'react'

import Header from 'sections/Header'
import Footer from 'sections/Footer'
import About from 'sections/About'

import Portfolio from 'sections/Portfolio'

type Props = {
  children: ReactNode
}

const Layout = (props: Props) => {
  return (
    <>
      <Head>
        <title>Daniel Huanca</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='min-h-screen flex flex-col'>
        <Header/>
        <main className='flex flex-grow items-center'>
          {props.children}
        </main>
        
      </div>
      <Portfolio/>
      <About/>
      <Footer/>
    </>
  )
}

export default Layout